linter:
  rules:
    # ------ Disable individual rules ----- #
    #                 ---                   #
    # Turn off what you don't like.         #
    # ------------------------------------- #

    # ------ Enable individual rules ------ #
    #                 ---                   #
    # These rules here are good but too     #
    # opinionated to enable them by default #
    # ------------------------------------- #

    # Make constructors the first thing in every class
    - sort_constructors_first

    # The new tabs vs. spaces. Choose wisely
    - prefer_single_quotes

    # Back to the 80s
    - lines_longer_than_80_chars

    - avoid_dynamic_calls

    - avoid_annotating_with_dynamic